publish = false
push-remote = "origin"
tag-name = "v{{version}}"
pre-release-replacements = [
  { file = "README.md", search = "version-\\d+\\.\\d+\\.\\d+-blue", replace = "version-{{version}}-blue" },
]
